// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "interpolate_image.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic interpolate_image::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic interpolate_image::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<50> interpolate_image::ap_ST_fsm_state1 = "1";
const sc_lv<50> interpolate_image::ap_ST_fsm_state2 = "10";
const sc_lv<50> interpolate_image::ap_ST_fsm_state3 = "100";
const sc_lv<50> interpolate_image::ap_ST_fsm_state4 = "1000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state5 = "10000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state6 = "100000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state7 = "1000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state8 = "10000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state9 = "100000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state10 = "1000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state11 = "10000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state12 = "100000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<50> interpolate_image::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<32> interpolate_image::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> interpolate_image::ap_const_lv32_4 = "100";
const sc_lv<32> interpolate_image::ap_const_lv32_B = "1011";
const sc_lv<32> interpolate_image::ap_const_lv32_13 = "10011";
const sc_lv<32> interpolate_image::ap_const_lv32_21 = "100001";
const sc_lv<32> interpolate_image::ap_const_lv32_E = "1110";
const sc_lv<32> interpolate_image::ap_const_lv32_24 = "100100";
const sc_lv<32> interpolate_image::ap_const_lv32_2B = "101011";
const sc_lv<32> interpolate_image::ap_const_lv32_1D = "11101";
const sc_lv<32> interpolate_image::ap_const_lv32_1E = "11110";
const sc_lv<32> interpolate_image::ap_const_lv32_25 = "100101";
const sc_lv<32> interpolate_image::ap_const_lv32_2C = "101100";
const sc_lv<32> interpolate_image::ap_const_lv32_1 = "1";
const sc_lv<32> interpolate_image::ap_const_lv32_7 = "111";
const sc_lv<32> interpolate_image::ap_const_lv32_8 = "1000";
const sc_lv<1> interpolate_image::ap_const_lv1_0 = "0";
const sc_lv<32> interpolate_image::ap_const_lv32_F = "1111";
const sc_lv<32> interpolate_image::ap_const_lv32_17 = "10111";
const sc_lv<32> interpolate_image::ap_const_lv32_1A = "11010";
const sc_lv<32> interpolate_image::ap_const_lv32_1B = "11011";
const sc_lv<32> interpolate_image::ap_const_lv32_1C = "11100";
const sc_lv<32> interpolate_image::ap_const_lv32_1F = "11111";
const sc_lv<32> interpolate_image::ap_const_lv32_22 = "100010";
const sc_lv<32> interpolate_image::ap_const_lv32_28 = "101000";
const sc_lv<32> interpolate_image::ap_const_lv32_29 = "101001";
const sc_lv<32> interpolate_image::ap_const_lv32_30 = "110000";
const sc_lv<8> interpolate_image::ap_const_lv8_0 = "00000000";
const sc_lv<1> interpolate_image::ap_const_lv1_1 = "1";
const sc_lv<9> interpolate_image::ap_const_lv9_0 = "000000000";
const sc_lv<2> interpolate_image::ap_const_lv2_0 = "00";
const sc_lv<32> interpolate_image::ap_const_lv32_31 = "110001";
const sc_lv<32> interpolate_image::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<32> interpolate_image::ap_const_lv32_14 = "10100";
const sc_lv<32> interpolate_image::ap_const_lv32_18 = "11000";
const sc_lv<32> interpolate_image::ap_const_lv32_26 = "100110";
const sc_lv<32> interpolate_image::ap_const_lv32_2D = "101101";
const sc_lv<32> interpolate_image::ap_const_lv32_40210000 = "1000000001000010000000000000000";
const sc_lv<32> interpolate_image::ap_const_lv32_3FD88000 = "111111110110001000000000000000";
const sc_lv<32> interpolate_image::ap_const_lv32_5 = "101";
const sc_lv<32> interpolate_image::ap_const_lv32_C = "1100";
const sc_lv<32> interpolate_image::ap_const_lv32_23 = "100011";
const sc_lv<32> interpolate_image::ap_const_lv32_2A = "101010";
const sc_lv<32> interpolate_image::ap_const_lv32_10 = "10000";
const sc_lv<8> interpolate_image::ap_const_lv8_80 = "10000000";
const sc_lv<8> interpolate_image::ap_const_lv8_1 = "1";
const sc_lv<9> interpolate_image::ap_const_lv9_100 = "100000000";
const sc_lv<9> interpolate_image::ap_const_lv9_1 = "1";
const sc_lv<9> interpolate_image::ap_const_lv9_181 = "110000001";
const sc_lv<8> interpolate_image::ap_const_lv8_7F = "1111111";
const sc_lv<32> interpolate_image::ap_const_lv32_37 = "110111";
const sc_lv<41> interpolate_image::ap_const_lv41_1B2 = "110110010";
const sc_lv<2> interpolate_image::ap_const_lv2_3 = "11";
const sc_lv<2> interpolate_image::ap_const_lv2_1 = "1";
const bool interpolate_image::ap_const_boolean_1 = true;

interpolate_image::interpolate_image(sc_module_name name) : sc_module(name), mVcdFile(0) {
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1 = new interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1");
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->clk(ap_clk);
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->reset(ap_rst);
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->din0(grp_fu_178_p0);
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->din1(grp_fu_178_p1);
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->opcode(grp_fu_178_opcode);
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->ce(ap_var_for_const0);
    interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1->dout(grp_fu_178_p2);
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2 = new interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2");
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2->clk(ap_clk);
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2->reset(ap_rst);
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2->din0(grp_fu_182_p0);
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2->din1(grp_fu_182_p1);
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2->ce(ap_var_for_const0);
    interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2->dout(grp_fu_182_p2);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3 = new interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1<1,3,32,32,32>("interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3");
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3->clk(ap_clk);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3->reset(ap_rst);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3->din0(grp_fu_188_p0);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3->din1(grp_fu_188_p1);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3->ce(ap_var_for_const0);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3->dout(grp_fu_188_p2);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4 = new interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1<1,3,32,32,32>("interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4");
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4->clk(ap_clk);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4->reset(ap_rst);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4->din0(grp_fu_194_p0);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4->din1(dx_reg_1022);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4->ce(ap_var_for_const0);
    interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4->dout(grp_fu_194_p2);
    interpolate_image_sitofp_32ns_32_4_1_U5 = new interpolate_image_sitofp_32ns_32_4_1<1,4,32,32>("interpolate_image_sitofp_32ns_32_4_1_U5");
    interpolate_image_sitofp_32ns_32_4_1_U5->clk(ap_clk);
    interpolate_image_sitofp_32ns_32_4_1_U5->reset(ap_rst);
    interpolate_image_sitofp_32ns_32_4_1_U5->din0(grp_fu_198_p0);
    interpolate_image_sitofp_32ns_32_4_1_U5->ce(ap_var_for_const0);
    interpolate_image_sitofp_32ns_32_4_1_U5->dout(grp_fu_198_p1);
    interpolate_image_sitofp_32s_32_4_1_U6 = new interpolate_image_sitofp_32s_32_4_1<1,4,32,32>("interpolate_image_sitofp_32s_32_4_1_U6");
    interpolate_image_sitofp_32s_32_4_1_U6->clk(ap_clk);
    interpolate_image_sitofp_32s_32_4_1_U6->reset(ap_rst);
    interpolate_image_sitofp_32s_32_4_1_U6->din0(grp_fu_201_p0);
    interpolate_image_sitofp_32s_32_4_1_U6->ce(ap_var_for_const0);
    interpolate_image_sitofp_32s_32_4_1_U6->dout(grp_fu_201_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln26_1_fu_621_p2);
    sensitive << ( mul_ln26_reg_1034 );
    sensitive << ( sext_ln26_fu_618_p1 );

    SC_METHOD(thread_add_ln26_2_fu_657_p2);
    sensitive << ( mul_ln26_reg_1034 );
    sensitive << ( sext_ln26_2_fu_653_p1 );

    SC_METHOD(thread_add_ln26_3_fu_758_p2);
    sensitive << ( sub_ln26_reg_1046 );
    sensitive << ( zext_ln26_3_fu_754_p1 );

    SC_METHOD(thread_add_ln26_4_fu_768_p2);
    sensitive << ( sub_ln26_1_reg_1056 );
    sensitive << ( zext_ln26_3_fu_754_p1 );

    SC_METHOD(thread_add_ln26_fu_648_p2);
    sensitive << ( p_Val2_15_reg_1008 );

    SC_METHOD(thread_add_ln29_1_fu_684_p2);
    sensitive << ( mul_ln29_reg_1040 );
    sensitive << ( sext_ln26_fu_618_p1 );

    SC_METHOD(thread_add_ln29_2_fu_711_p2);
    sensitive << ( mul_ln29_reg_1040 );
    sensitive << ( sext_ln26_2_fu_653_p1 );

    SC_METHOD(thread_add_ln29_3_fu_778_p2);
    sensitive << ( sub_ln29_reg_1061 );
    sensitive << ( zext_ln26_3_fu_754_p1 );

    SC_METHOD(thread_add_ln29_4_fu_783_p2);
    sensitive << ( sub_ln29_1_reg_1066 );
    sensitive << ( zext_ln26_3_fu_754_p1 );

    SC_METHOD(thread_add_ln29_fu_603_p2);
    sensitive << ( p_Val2_17_reg_1015 );

    SC_METHOD(thread_add_ln31_1_fu_788_p2);
    sensitive << ( sub_ln31_reg_1003 );
    sensitive << ( zext_ln26_2_fu_750_p1 );

    SC_METHOD(thread_add_ln31_fu_309_p2);
    sensitive << ( zext_ln310_reg_963 );
    sensitive << ( zext_ln31_fu_305_p1 );

    SC_METHOD(thread_add_ln339_1_fu_496_p2);
    sensitive << ( zext_ln339_1_fu_493_p1 );

    SC_METHOD(thread_add_ln339_2_fu_859_p2);
    sensitive << ( zext_ln339_2_fu_856_p1 );

    SC_METHOD(thread_add_ln339_fu_380_p2);
    sensitive << ( zext_ln339_fu_376_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state44);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state49);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state50);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_240_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_240_p2 );

    SC_METHOD(thread_c_fu_744_p2);
    sensitive << ( c_0_reg_167 );

    SC_METHOD(thread_grp_fu_178_opcode);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state39 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_grp_fu_178_p0);
    sensitive << ( reg_210 );
    sensitive << ( reg_229 );
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state39 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_grp_fu_178_p1);
    sensitive << ( reg_204 );
    sensitive << ( reg_229 );
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( dx_reg_1022 );
    sensitive << ( tmp_1_reg_1149 );
    sensitive << ( tmp_12_reg_1154 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( ap_CS_fsm_state39 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_grp_fu_182_p0);
    sensitive << ( x_assign_1_reg_958 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_grp_fu_182_p1);
    sensitive << ( reg_215 );
    sensitive << ( dy_reg_1028 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_grp_fu_188_p0);
    sensitive << ( reg_204 );
    sensitive << ( tmp_3_reg_1139 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( top_reg_1159 );
    sensitive << ( bottom_reg_1164 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_grp_fu_188_p1);
    sensitive << ( dy_reg_1028 );
    sensitive << ( tmp_6_reg_1051 );
    sensitive << ( tmp_7_reg_1071 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_grp_fu_194_p0);
    sensitive << ( reg_215 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( tmp_11_reg_1144 );
    sensitive << ( ap_CS_fsm_state36 );

    SC_METHOD(thread_grp_fu_198_p0);
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( zext_ln16_fu_235_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln17_fu_276_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( p_Val2_15_reg_1008 );
    sensitive << ( zext_ln26_fu_801_p1 );
    sensitive << ( zext_ln29_fu_811_p1 );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_201_p0);
    sensitive << ( ap_CS_fsm_state31 );
    sensitive << ( p_Val2_17_reg_1015 );
    sensitive << ( zext_ln26_1_fu_806_p1 );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( zext_ln29_1_fu_816_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_icmp_ln16_fu_240_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( y_0_reg_144 );

    SC_METHOD(thread_icmp_ln17_fu_281_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_icmp_ln21_fu_738_p2);
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( c_0_reg_167 );

    SC_METHOD(thread_input_image_address0);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( zext_ln26_4_fu_763_p1 );
    sensitive << ( zext_ln29_2_fu_793_p1 );

    SC_METHOD(thread_input_image_address1);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( zext_ln26_5_fu_773_p1 );
    sensitive << ( zext_ln29_3_fu_797_p1 );

    SC_METHOD(thread_input_image_ce0);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_input_image_ce1);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state29 );

    SC_METHOD(thread_isNeg_1_fu_502_p3);
    sensitive << ( add_ln339_1_fu_496_p2 );

    SC_METHOD(thread_isNeg_2_fu_865_p3);
    sensitive << ( add_ln339_2_fu_859_p2 );

    SC_METHOD(thread_isNeg_fu_386_p3);
    sensitive << ( add_ln339_fu_380_p2 );

    SC_METHOD(thread_mantissa_V_1_fu_480_p4);
    sensitive << ( tmp_V_3_reg_998 );

    SC_METHOD(thread_mantissa_V_2_fu_843_p4);
    sensitive << ( tmp_V_5_reg_1175 );

    SC_METHOD(thread_mantissa_V_fu_362_p4);
    sensitive << ( tmp_V_1_fu_358_p1 );

    SC_METHOD(thread_mul_ln26_fu_597_p1);
    sensitive << ( p_Val2_17_reg_1015 );
    sensitive << ( ap_CS_fsm_state27 );

    SC_METHOD(thread_mul_ln26_fu_597_p2);
    sensitive << ( mul_ln26_fu_597_p1 );

    SC_METHOD(thread_mul_ln29_fu_612_p1);
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( add_ln29_fu_603_p2 );

    SC_METHOD(thread_mul_ln29_fu_612_p2);
    sensitive << ( mul_ln29_fu_612_p1 );

    SC_METHOD(thread_output_image_address0);
    sensitive << ( ap_CS_fsm_state50 );
    sensitive << ( zext_ln31_2_fu_839_p1 );

    SC_METHOD(thread_output_image_ce0);
    sensitive << ( ap_CS_fsm_state50 );

    SC_METHOD(thread_output_image_d0);
    sensitive << ( ap_CS_fsm_state50 );
    sensitive << ( isNeg_2_fu_865_p3 );
    sensitive << ( zext_ln662_2_fu_922_p1 );
    sensitive << ( tmp_19_fu_926_p4 );

    SC_METHOD(thread_output_image_we0);
    sensitive << ( ap_CS_fsm_state50 );

    SC_METHOD(thread_p_Result_s_fu_340_p3);
    sensitive << ( p_Val2_s_fu_336_p1 );

    SC_METHOD(thread_p_Val2_10_fu_821_p1);
    sensitive << ( grp_fu_178_p2 );

    SC_METHOD(thread_p_Val2_14_fu_458_p3);
    sensitive << ( isNeg_fu_386_p3 );
    sensitive << ( zext_ln662_fu_444_p1 );
    sensitive << ( tmp_17_fu_448_p4 );

    SC_METHOD(thread_p_Val2_15_fu_472_p3);
    sensitive << ( p_Val2_14_fu_458_p3 );
    sensitive << ( p_Result_s_fu_340_p3 );
    sensitive << ( result_V_1_fu_466_p2 );

    SC_METHOD(thread_p_Val2_16_fu_573_p3);
    sensitive << ( isNeg_1_fu_502_p3 );
    sensitive << ( zext_ln662_1_fu_559_p1 );
    sensitive << ( tmp_18_fu_563_p4 );

    SC_METHOD(thread_p_Val2_17_fu_587_p3);
    sensitive << ( p_Result_1_reg_974 );
    sensitive << ( p_Val2_16_fu_573_p3 );
    sensitive << ( result_V_3_fu_581_p2 );

    SC_METHOD(thread_p_Val2_5_fu_264_p1);
    sensitive << ( grp_fu_188_p2 );

    SC_METHOD(thread_p_Val2_s_fu_336_p1);
    sensitive << ( reg_210 );

    SC_METHOD(thread_p_shl1_cast_fu_724_p3);
    sensitive << ( trunc_ln29_3_fu_720_p1 );

    SC_METHOD(thread_p_shl2_cast_fu_697_p3);
    sensitive << ( trunc_ln29_1_fu_693_p1 );

    SC_METHOD(thread_p_shl3_cast_fu_670_p3);
    sensitive << ( trunc_ln26_3_fu_666_p1 );

    SC_METHOD(thread_p_shl4_cast_fu_634_p3);
    sensitive << ( trunc_ln26_1_fu_630_p1 );

    SC_METHOD(thread_p_shl_cast_fu_322_p3);
    sensitive << ( trunc_ln31_fu_318_p1 );

    SC_METHOD(thread_r_V_1_fu_430_p2);
    sensitive << ( zext_ln682_fu_372_p1 );
    sensitive << ( zext_ln1287_fu_420_p1 );

    SC_METHOD(thread_r_V_2_fu_539_p2);
    sensitive << ( mantissa_V_1_fu_480_p4 );
    sensitive << ( sext_ln1311_7_fu_531_p1 );

    SC_METHOD(thread_r_V_3_fu_545_p2);
    sensitive << ( zext_ln682_1_fu_489_p1 );
    sensitive << ( zext_ln1287_1_fu_535_p1 );

    SC_METHOD(thread_r_V_4_fu_902_p2);
    sensitive << ( mantissa_V_2_fu_843_p4 );
    sensitive << ( sext_ln1311_8_fu_894_p1 );

    SC_METHOD(thread_r_V_5_fu_908_p2);
    sensitive << ( zext_ln682_2_fu_852_p1 );
    sensitive << ( zext_ln1287_2_fu_898_p1 );

    SC_METHOD(thread_r_V_fu_424_p2);
    sensitive << ( mantissa_V_fu_362_p4 );
    sensitive << ( sext_ln1311_6_fu_416_p1 );

    SC_METHOD(thread_result_V_1_fu_466_p2);
    sensitive << ( p_Val2_14_fu_458_p3 );

    SC_METHOD(thread_result_V_3_fu_581_p2);
    sensitive << ( p_Val2_16_fu_573_p3 );

    SC_METHOD(thread_sext_ln1311_1_fu_412_p1);
    sensitive << ( ush_fu_404_p3 );

    SC_METHOD(thread_sext_ln1311_2_fu_515_p1);
    sensitive << ( sub_ln1311_1_fu_510_p2 );

    SC_METHOD(thread_sext_ln1311_3_fu_527_p1);
    sensitive << ( ush_1_fu_519_p3 );

    SC_METHOD(thread_sext_ln1311_4_fu_878_p1);
    sensitive << ( sub_ln1311_2_fu_873_p2 );

    SC_METHOD(thread_sext_ln1311_5_fu_890_p1);
    sensitive << ( ush_2_fu_882_p3 );

    SC_METHOD(thread_sext_ln1311_6_fu_416_p1);
    sensitive << ( ush_fu_404_p3 );

    SC_METHOD(thread_sext_ln1311_7_fu_531_p1);
    sensitive << ( ush_1_fu_519_p3 );

    SC_METHOD(thread_sext_ln1311_8_fu_894_p1);
    sensitive << ( ush_2_fu_882_p3 );

    SC_METHOD(thread_sext_ln1311_fu_400_p1);
    sensitive << ( sub_ln1311_fu_394_p2 );

    SC_METHOD(thread_sext_ln26_2_fu_653_p1);
    sensitive << ( add_ln26_fu_648_p2 );

    SC_METHOD(thread_sext_ln26_fu_618_p1);
    sensitive << ( p_Val2_15_reg_1008 );

    SC_METHOD(thread_sub_ln1311_1_fu_510_p2);
    sensitive << ( tmp_V_2_reg_992 );

    SC_METHOD(thread_sub_ln1311_2_fu_873_p2);
    sensitive << ( tmp_V_4_reg_1169 );

    SC_METHOD(thread_sub_ln1311_fu_394_p2);
    sensitive << ( tmp_V_fu_348_p4 );

    SC_METHOD(thread_sub_ln26_1_fu_678_p2);
    sensitive << ( p_shl3_cast_fu_670_p3 );
    sensitive << ( trunc_ln26_2_fu_662_p1 );

    SC_METHOD(thread_sub_ln26_fu_642_p2);
    sensitive << ( p_shl4_cast_fu_634_p3 );
    sensitive << ( trunc_ln26_fu_626_p1 );

    SC_METHOD(thread_sub_ln29_1_fu_732_p2);
    sensitive << ( p_shl1_cast_fu_724_p3 );
    sensitive << ( trunc_ln29_2_fu_716_p1 );

    SC_METHOD(thread_sub_ln29_fu_705_p2);
    sensitive << ( p_shl2_cast_fu_697_p3 );
    sensitive << ( trunc_ln29_fu_689_p1 );

    SC_METHOD(thread_sub_ln31_fu_330_p2);
    sensitive << ( p_shl_cast_fu_322_p3 );
    sensitive << ( zext_ln31_1_fu_314_p1 );

    SC_METHOD(thread_tmp_15_fu_252_p3);
    sensitive << ( y_0_reg_144 );

    SC_METHOD(thread_tmp_17_fu_448_p4);
    sensitive << ( r_V_1_fu_430_p2 );

    SC_METHOD(thread_tmp_18_fu_563_p4);
    sensitive << ( r_V_3_fu_545_p2 );

    SC_METHOD(thread_tmp_19_fu_926_p4);
    sensitive << ( r_V_5_fu_908_p2 );

    SC_METHOD(thread_tmp_21_fu_436_p3);
    sensitive << ( r_V_fu_424_p2 );

    SC_METHOD(thread_tmp_23_fu_551_p3);
    sensitive << ( r_V_2_fu_539_p2 );

    SC_METHOD(thread_tmp_27_fu_914_p3);
    sensitive << ( r_V_4_fu_902_p2 );

    SC_METHOD(thread_tmp_V_1_fu_358_p1);
    sensitive << ( p_Val2_s_fu_336_p1 );

    SC_METHOD(thread_tmp_V_3_fu_302_p1);
    sensitive << ( p_Val2_5_reg_968 );

    SC_METHOD(thread_tmp_V_5_fu_835_p1);
    sensitive << ( p_Val2_10_fu_821_p1 );

    SC_METHOD(thread_tmp_V_fu_348_p4);
    sensitive << ( p_Val2_s_fu_336_p1 );

    SC_METHOD(thread_trunc_ln26_1_fu_630_p1);
    sensitive << ( add_ln26_1_fu_621_p2 );

    SC_METHOD(thread_trunc_ln26_2_fu_662_p1);
    sensitive << ( add_ln26_2_fu_657_p2 );

    SC_METHOD(thread_trunc_ln26_3_fu_666_p1);
    sensitive << ( add_ln26_2_fu_657_p2 );

    SC_METHOD(thread_trunc_ln26_fu_626_p1);
    sensitive << ( add_ln26_1_fu_621_p2 );

    SC_METHOD(thread_trunc_ln29_1_fu_693_p1);
    sensitive << ( add_ln29_1_fu_684_p2 );

    SC_METHOD(thread_trunc_ln29_2_fu_716_p1);
    sensitive << ( add_ln29_2_fu_711_p2 );

    SC_METHOD(thread_trunc_ln29_3_fu_720_p1);
    sensitive << ( add_ln29_2_fu_711_p2 );

    SC_METHOD(thread_trunc_ln29_fu_689_p1);
    sensitive << ( add_ln29_1_fu_684_p2 );

    SC_METHOD(thread_trunc_ln31_fu_318_p1);
    sensitive << ( add_ln31_fu_309_p2 );

    SC_METHOD(thread_ush_1_fu_519_p3);
    sensitive << ( add_ln339_1_fu_496_p2 );
    sensitive << ( isNeg_1_fu_502_p3 );
    sensitive << ( sext_ln1311_2_fu_515_p1 );

    SC_METHOD(thread_ush_2_fu_882_p3);
    sensitive << ( add_ln339_2_fu_859_p2 );
    sensitive << ( isNeg_2_fu_865_p3 );
    sensitive << ( sext_ln1311_4_fu_878_p1 );

    SC_METHOD(thread_ush_fu_404_p3);
    sensitive << ( add_ln339_fu_380_p2 );
    sensitive << ( isNeg_fu_386_p3 );
    sensitive << ( sext_ln1311_fu_400_p1 );

    SC_METHOD(thread_x_fu_287_p2);
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_y_fu_246_p2);
    sensitive << ( y_0_reg_144 );

    SC_METHOD(thread_zext_ln1287_1_fu_535_p1);
    sensitive << ( sext_ln1311_3_fu_527_p1 );

    SC_METHOD(thread_zext_ln1287_2_fu_898_p1);
    sensitive << ( sext_ln1311_5_fu_890_p1 );

    SC_METHOD(thread_zext_ln1287_fu_420_p1);
    sensitive << ( sext_ln1311_1_fu_412_p1 );

    SC_METHOD(thread_zext_ln16_fu_235_p1);
    sensitive << ( y_0_reg_144 );

    SC_METHOD(thread_zext_ln17_fu_276_p1);
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_zext_ln26_1_fu_806_p1);
    sensitive << ( reg_225 );

    SC_METHOD(thread_zext_ln26_2_fu_750_p1);
    sensitive << ( c_0_reg_167 );

    SC_METHOD(thread_zext_ln26_3_fu_754_p1);
    sensitive << ( c_0_reg_167 );

    SC_METHOD(thread_zext_ln26_4_fu_763_p1);
    sensitive << ( add_ln26_3_fu_758_p2 );

    SC_METHOD(thread_zext_ln26_5_fu_773_p1);
    sensitive << ( add_ln26_4_fu_768_p2 );

    SC_METHOD(thread_zext_ln26_fu_801_p1);
    sensitive << ( reg_221 );

    SC_METHOD(thread_zext_ln29_1_fu_816_p1);
    sensitive << ( reg_225 );

    SC_METHOD(thread_zext_ln29_2_fu_793_p1);
    sensitive << ( add_ln29_3_reg_1094 );

    SC_METHOD(thread_zext_ln29_3_fu_797_p1);
    sensitive << ( add_ln29_4_reg_1099 );

    SC_METHOD(thread_zext_ln29_fu_811_p1);
    sensitive << ( reg_221 );

    SC_METHOD(thread_zext_ln310_fu_260_p1);
    sensitive << ( tmp_15_fu_252_p3 );

    SC_METHOD(thread_zext_ln31_1_fu_314_p1);
    sensitive << ( add_ln31_fu_309_p2 );

    SC_METHOD(thread_zext_ln31_2_fu_839_p1);
    sensitive << ( add_ln31_1_reg_1104 );

    SC_METHOD(thread_zext_ln31_fu_305_p1);
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_zext_ln339_1_fu_493_p1);
    sensitive << ( tmp_V_2_reg_992 );

    SC_METHOD(thread_zext_ln339_2_fu_856_p1);
    sensitive << ( tmp_V_4_reg_1169 );

    SC_METHOD(thread_zext_ln339_fu_376_p1);
    sensitive << ( tmp_V_fu_348_p4 );

    SC_METHOD(thread_zext_ln662_1_fu_559_p1);
    sensitive << ( tmp_23_fu_551_p3 );

    SC_METHOD(thread_zext_ln662_2_fu_922_p1);
    sensitive << ( tmp_27_fu_914_p3 );

    SC_METHOD(thread_zext_ln662_fu_444_p1);
    sensitive << ( tmp_21_fu_436_p3 );

    SC_METHOD(thread_zext_ln682_1_fu_489_p1);
    sensitive << ( mantissa_V_1_fu_480_p4 );

    SC_METHOD(thread_zext_ln682_2_fu_852_p1);
    sensitive << ( mantissa_V_2_fu_843_p4 );

    SC_METHOD(thread_zext_ln682_fu_372_p1);
    sensitive << ( mantissa_V_fu_362_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln17_fu_281_p2 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( icmp_ln21_fu_738_p2 );
    sensitive << ( icmp_ln16_fu_240_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "interpolate_image_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_image_address0, "(port)input_image_address0");
    sc_trace(mVcdFile, input_image_ce0, "(port)input_image_ce0");
    sc_trace(mVcdFile, input_image_q0, "(port)input_image_q0");
    sc_trace(mVcdFile, input_image_address1, "(port)input_image_address1");
    sc_trace(mVcdFile, input_image_ce1, "(port)input_image_ce1");
    sc_trace(mVcdFile, input_image_q1, "(port)input_image_q1");
    sc_trace(mVcdFile, output_image_address0, "(port)output_image_address0");
    sc_trace(mVcdFile, output_image_ce0, "(port)output_image_ce0");
    sc_trace(mVcdFile, output_image_we0, "(port)output_image_we0");
    sc_trace(mVcdFile, output_image_d0, "(port)output_image_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_198_p1, "grp_fu_198_p1");
    sc_trace(mVcdFile, reg_204, "reg_204");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, grp_fu_188_p2, "grp_fu_188_p2");
    sc_trace(mVcdFile, reg_210, "reg_210");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, ap_CS_fsm_state44, "ap_CS_fsm_state44");
    sc_trace(mVcdFile, grp_fu_201_p1, "grp_fu_201_p1");
    sc_trace(mVcdFile, reg_215, "reg_215");
    sc_trace(mVcdFile, reg_221, "reg_221");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, reg_225, "reg_225");
    sc_trace(mVcdFile, reg_229, "reg_229");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, ap_CS_fsm_state45, "ap_CS_fsm_state45");
    sc_trace(mVcdFile, zext_ln16_fu_235_p1, "zext_ln16_fu_235_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, y_fu_246_p2, "y_fu_246_p2");
    sc_trace(mVcdFile, y_reg_953, "y_reg_953");
    sc_trace(mVcdFile, x_assign_1_reg_958, "x_assign_1_reg_958");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, zext_ln310_fu_260_p1, "zext_ln310_fu_260_p1");
    sc_trace(mVcdFile, zext_ln310_reg_963, "zext_ln310_reg_963");
    sc_trace(mVcdFile, p_Val2_5_fu_264_p1, "p_Val2_5_fu_264_p1");
    sc_trace(mVcdFile, p_Val2_5_reg_968, "p_Val2_5_reg_968");
    sc_trace(mVcdFile, p_Result_1_reg_974, "p_Result_1_reg_974");
    sc_trace(mVcdFile, zext_ln17_fu_276_p1, "zext_ln17_fu_276_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, x_fu_287_p2, "x_fu_287_p2");
    sc_trace(mVcdFile, x_reg_987, "x_reg_987");
    sc_trace(mVcdFile, tmp_V_2_reg_992, "tmp_V_2_reg_992");
    sc_trace(mVcdFile, icmp_ln17_fu_281_p2, "icmp_ln17_fu_281_p2");
    sc_trace(mVcdFile, tmp_V_3_fu_302_p1, "tmp_V_3_fu_302_p1");
    sc_trace(mVcdFile, tmp_V_3_reg_998, "tmp_V_3_reg_998");
    sc_trace(mVcdFile, sub_ln31_fu_330_p2, "sub_ln31_fu_330_p2");
    sc_trace(mVcdFile, sub_ln31_reg_1003, "sub_ln31_reg_1003");
    sc_trace(mVcdFile, p_Val2_15_fu_472_p3, "p_Val2_15_fu_472_p3");
    sc_trace(mVcdFile, p_Val2_15_reg_1008, "p_Val2_15_reg_1008");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, p_Val2_17_fu_587_p3, "p_Val2_17_fu_587_p3");
    sc_trace(mVcdFile, p_Val2_17_reg_1015, "p_Val2_17_reg_1015");
    sc_trace(mVcdFile, grp_fu_178_p2, "grp_fu_178_p2");
    sc_trace(mVcdFile, dx_reg_1022, "dx_reg_1022");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_182_p2, "grp_fu_182_p2");
    sc_trace(mVcdFile, dy_reg_1028, "dy_reg_1028");
    sc_trace(mVcdFile, mul_ln26_fu_597_p2, "mul_ln26_fu_597_p2");
    sc_trace(mVcdFile, mul_ln26_reg_1034, "mul_ln26_reg_1034");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, mul_ln29_fu_612_p2, "mul_ln29_fu_612_p2");
    sc_trace(mVcdFile, mul_ln29_reg_1040, "mul_ln29_reg_1040");
    sc_trace(mVcdFile, sub_ln26_fu_642_p2, "sub_ln26_fu_642_p2");
    sc_trace(mVcdFile, sub_ln26_reg_1046, "sub_ln26_reg_1046");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, tmp_6_reg_1051, "tmp_6_reg_1051");
    sc_trace(mVcdFile, sub_ln26_1_fu_678_p2, "sub_ln26_1_fu_678_p2");
    sc_trace(mVcdFile, sub_ln26_1_reg_1056, "sub_ln26_1_reg_1056");
    sc_trace(mVcdFile, sub_ln29_fu_705_p2, "sub_ln29_fu_705_p2");
    sc_trace(mVcdFile, sub_ln29_reg_1061, "sub_ln29_reg_1061");
    sc_trace(mVcdFile, sub_ln29_1_fu_732_p2, "sub_ln29_1_fu_732_p2");
    sc_trace(mVcdFile, sub_ln29_1_reg_1066, "sub_ln29_1_reg_1066");
    sc_trace(mVcdFile, tmp_7_reg_1071, "tmp_7_reg_1071");
    sc_trace(mVcdFile, c_fu_744_p2, "c_fu_744_p2");
    sc_trace(mVcdFile, c_reg_1079, "c_reg_1079");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, icmp_ln21_fu_738_p2, "icmp_ln21_fu_738_p2");
    sc_trace(mVcdFile, add_ln29_3_fu_778_p2, "add_ln29_3_fu_778_p2");
    sc_trace(mVcdFile, add_ln29_3_reg_1094, "add_ln29_3_reg_1094");
    sc_trace(mVcdFile, add_ln29_4_fu_783_p2, "add_ln29_4_fu_783_p2");
    sc_trace(mVcdFile, add_ln29_4_reg_1099, "add_ln29_4_reg_1099");
    sc_trace(mVcdFile, add_ln31_1_fu_788_p2, "add_ln31_1_fu_788_p2");
    sc_trace(mVcdFile, add_ln31_1_reg_1104, "add_ln31_1_reg_1104");
    sc_trace(mVcdFile, zext_ln26_fu_801_p1, "zext_ln26_fu_801_p1");
    sc_trace(mVcdFile, zext_ln26_1_fu_806_p1, "zext_ln26_1_fu_806_p1");
    sc_trace(mVcdFile, zext_ln29_fu_811_p1, "zext_ln29_fu_811_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, zext_ln29_1_fu_816_p1, "zext_ln29_1_fu_816_p1");
    sc_trace(mVcdFile, tmp_3_reg_1139, "tmp_3_reg_1139");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, tmp_11_reg_1144, "tmp_11_reg_1144");
    sc_trace(mVcdFile, grp_fu_194_p2, "grp_fu_194_p2");
    sc_trace(mVcdFile, tmp_1_reg_1149, "tmp_1_reg_1149");
    sc_trace(mVcdFile, tmp_12_reg_1154, "tmp_12_reg_1154");
    sc_trace(mVcdFile, top_reg_1159, "top_reg_1159");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, bottom_reg_1164, "bottom_reg_1164");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, tmp_V_4_reg_1169, "tmp_V_4_reg_1169");
    sc_trace(mVcdFile, ap_CS_fsm_state49, "ap_CS_fsm_state49");
    sc_trace(mVcdFile, tmp_V_5_fu_835_p1, "tmp_V_5_fu_835_p1");
    sc_trace(mVcdFile, tmp_V_5_reg_1175, "tmp_V_5_reg_1175");
    sc_trace(mVcdFile, y_0_reg_144, "y_0_reg_144");
    sc_trace(mVcdFile, x_0_reg_156, "x_0_reg_156");
    sc_trace(mVcdFile, c_0_reg_167, "c_0_reg_167");
    sc_trace(mVcdFile, ap_CS_fsm_state50, "ap_CS_fsm_state50");
    sc_trace(mVcdFile, zext_ln26_4_fu_763_p1, "zext_ln26_4_fu_763_p1");
    sc_trace(mVcdFile, zext_ln26_5_fu_773_p1, "zext_ln26_5_fu_773_p1");
    sc_trace(mVcdFile, zext_ln29_2_fu_793_p1, "zext_ln29_2_fu_793_p1");
    sc_trace(mVcdFile, zext_ln29_3_fu_797_p1, "zext_ln29_3_fu_797_p1");
    sc_trace(mVcdFile, zext_ln31_2_fu_839_p1, "zext_ln31_2_fu_839_p1");
    sc_trace(mVcdFile, grp_fu_178_p0, "grp_fu_178_p0");
    sc_trace(mVcdFile, grp_fu_178_p1, "grp_fu_178_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, ap_CS_fsm_state39, "ap_CS_fsm_state39");
    sc_trace(mVcdFile, ap_CS_fsm_state46, "ap_CS_fsm_state46");
    sc_trace(mVcdFile, grp_fu_182_p0, "grp_fu_182_p0");
    sc_trace(mVcdFile, grp_fu_182_p1, "grp_fu_182_p1");
    sc_trace(mVcdFile, grp_fu_188_p0, "grp_fu_188_p0");
    sc_trace(mVcdFile, grp_fu_188_p1, "grp_fu_188_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, grp_fu_194_p0, "grp_fu_194_p0");
    sc_trace(mVcdFile, grp_fu_198_p0, "grp_fu_198_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_201_p0, "grp_fu_201_p0");
    sc_trace(mVcdFile, tmp_15_fu_252_p3, "tmp_15_fu_252_p3");
    sc_trace(mVcdFile, zext_ln31_fu_305_p1, "zext_ln31_fu_305_p1");
    sc_trace(mVcdFile, add_ln31_fu_309_p2, "add_ln31_fu_309_p2");
    sc_trace(mVcdFile, trunc_ln31_fu_318_p1, "trunc_ln31_fu_318_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_322_p3, "p_shl_cast_fu_322_p3");
    sc_trace(mVcdFile, zext_ln31_1_fu_314_p1, "zext_ln31_1_fu_314_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_336_p1, "p_Val2_s_fu_336_p1");
    sc_trace(mVcdFile, tmp_V_1_fu_358_p1, "tmp_V_1_fu_358_p1");
    sc_trace(mVcdFile, mantissa_V_fu_362_p4, "mantissa_V_fu_362_p4");
    sc_trace(mVcdFile, tmp_V_fu_348_p4, "tmp_V_fu_348_p4");
    sc_trace(mVcdFile, zext_ln339_fu_376_p1, "zext_ln339_fu_376_p1");
    sc_trace(mVcdFile, add_ln339_fu_380_p2, "add_ln339_fu_380_p2");
    sc_trace(mVcdFile, sub_ln1311_fu_394_p2, "sub_ln1311_fu_394_p2");
    sc_trace(mVcdFile, isNeg_fu_386_p3, "isNeg_fu_386_p3");
    sc_trace(mVcdFile, sext_ln1311_fu_400_p1, "sext_ln1311_fu_400_p1");
    sc_trace(mVcdFile, ush_fu_404_p3, "ush_fu_404_p3");
    sc_trace(mVcdFile, sext_ln1311_1_fu_412_p1, "sext_ln1311_1_fu_412_p1");
    sc_trace(mVcdFile, sext_ln1311_6_fu_416_p1, "sext_ln1311_6_fu_416_p1");
    sc_trace(mVcdFile, zext_ln682_fu_372_p1, "zext_ln682_fu_372_p1");
    sc_trace(mVcdFile, zext_ln1287_fu_420_p1, "zext_ln1287_fu_420_p1");
    sc_trace(mVcdFile, r_V_fu_424_p2, "r_V_fu_424_p2");
    sc_trace(mVcdFile, tmp_21_fu_436_p3, "tmp_21_fu_436_p3");
    sc_trace(mVcdFile, r_V_1_fu_430_p2, "r_V_1_fu_430_p2");
    sc_trace(mVcdFile, zext_ln662_fu_444_p1, "zext_ln662_fu_444_p1");
    sc_trace(mVcdFile, tmp_17_fu_448_p4, "tmp_17_fu_448_p4");
    sc_trace(mVcdFile, p_Val2_14_fu_458_p3, "p_Val2_14_fu_458_p3");
    sc_trace(mVcdFile, p_Result_s_fu_340_p3, "p_Result_s_fu_340_p3");
    sc_trace(mVcdFile, result_V_1_fu_466_p2, "result_V_1_fu_466_p2");
    sc_trace(mVcdFile, mantissa_V_1_fu_480_p4, "mantissa_V_1_fu_480_p4");
    sc_trace(mVcdFile, zext_ln339_1_fu_493_p1, "zext_ln339_1_fu_493_p1");
    sc_trace(mVcdFile, add_ln339_1_fu_496_p2, "add_ln339_1_fu_496_p2");
    sc_trace(mVcdFile, sub_ln1311_1_fu_510_p2, "sub_ln1311_1_fu_510_p2");
    sc_trace(mVcdFile, isNeg_1_fu_502_p3, "isNeg_1_fu_502_p3");
    sc_trace(mVcdFile, sext_ln1311_2_fu_515_p1, "sext_ln1311_2_fu_515_p1");
    sc_trace(mVcdFile, ush_1_fu_519_p3, "ush_1_fu_519_p3");
    sc_trace(mVcdFile, sext_ln1311_3_fu_527_p1, "sext_ln1311_3_fu_527_p1");
    sc_trace(mVcdFile, sext_ln1311_7_fu_531_p1, "sext_ln1311_7_fu_531_p1");
    sc_trace(mVcdFile, zext_ln682_1_fu_489_p1, "zext_ln682_1_fu_489_p1");
    sc_trace(mVcdFile, zext_ln1287_1_fu_535_p1, "zext_ln1287_1_fu_535_p1");
    sc_trace(mVcdFile, r_V_2_fu_539_p2, "r_V_2_fu_539_p2");
    sc_trace(mVcdFile, tmp_23_fu_551_p3, "tmp_23_fu_551_p3");
    sc_trace(mVcdFile, r_V_3_fu_545_p2, "r_V_3_fu_545_p2");
    sc_trace(mVcdFile, zext_ln662_1_fu_559_p1, "zext_ln662_1_fu_559_p1");
    sc_trace(mVcdFile, tmp_18_fu_563_p4, "tmp_18_fu_563_p4");
    sc_trace(mVcdFile, p_Val2_16_fu_573_p3, "p_Val2_16_fu_573_p3");
    sc_trace(mVcdFile, result_V_3_fu_581_p2, "result_V_3_fu_581_p2");
    sc_trace(mVcdFile, mul_ln26_fu_597_p1, "mul_ln26_fu_597_p1");
    sc_trace(mVcdFile, add_ln29_fu_603_p2, "add_ln29_fu_603_p2");
    sc_trace(mVcdFile, mul_ln29_fu_612_p1, "mul_ln29_fu_612_p1");
    sc_trace(mVcdFile, sext_ln26_fu_618_p1, "sext_ln26_fu_618_p1");
    sc_trace(mVcdFile, add_ln26_1_fu_621_p2, "add_ln26_1_fu_621_p2");
    sc_trace(mVcdFile, trunc_ln26_1_fu_630_p1, "trunc_ln26_1_fu_630_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_634_p3, "p_shl4_cast_fu_634_p3");
    sc_trace(mVcdFile, trunc_ln26_fu_626_p1, "trunc_ln26_fu_626_p1");
    sc_trace(mVcdFile, add_ln26_fu_648_p2, "add_ln26_fu_648_p2");
    sc_trace(mVcdFile, sext_ln26_2_fu_653_p1, "sext_ln26_2_fu_653_p1");
    sc_trace(mVcdFile, add_ln26_2_fu_657_p2, "add_ln26_2_fu_657_p2");
    sc_trace(mVcdFile, trunc_ln26_3_fu_666_p1, "trunc_ln26_3_fu_666_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_670_p3, "p_shl3_cast_fu_670_p3");
    sc_trace(mVcdFile, trunc_ln26_2_fu_662_p1, "trunc_ln26_2_fu_662_p1");
    sc_trace(mVcdFile, add_ln29_1_fu_684_p2, "add_ln29_1_fu_684_p2");
    sc_trace(mVcdFile, trunc_ln29_1_fu_693_p1, "trunc_ln29_1_fu_693_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_697_p3, "p_shl2_cast_fu_697_p3");
    sc_trace(mVcdFile, trunc_ln29_fu_689_p1, "trunc_ln29_fu_689_p1");
    sc_trace(mVcdFile, add_ln29_2_fu_711_p2, "add_ln29_2_fu_711_p2");
    sc_trace(mVcdFile, trunc_ln29_3_fu_720_p1, "trunc_ln29_3_fu_720_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_724_p3, "p_shl1_cast_fu_724_p3");
    sc_trace(mVcdFile, trunc_ln29_2_fu_716_p1, "trunc_ln29_2_fu_716_p1");
    sc_trace(mVcdFile, zext_ln26_3_fu_754_p1, "zext_ln26_3_fu_754_p1");
    sc_trace(mVcdFile, add_ln26_3_fu_758_p2, "add_ln26_3_fu_758_p2");
    sc_trace(mVcdFile, add_ln26_4_fu_768_p2, "add_ln26_4_fu_768_p2");
    sc_trace(mVcdFile, zext_ln26_2_fu_750_p1, "zext_ln26_2_fu_750_p1");
    sc_trace(mVcdFile, p_Val2_10_fu_821_p1, "p_Val2_10_fu_821_p1");
    sc_trace(mVcdFile, mantissa_V_2_fu_843_p4, "mantissa_V_2_fu_843_p4");
    sc_trace(mVcdFile, zext_ln339_2_fu_856_p1, "zext_ln339_2_fu_856_p1");
    sc_trace(mVcdFile, add_ln339_2_fu_859_p2, "add_ln339_2_fu_859_p2");
    sc_trace(mVcdFile, sub_ln1311_2_fu_873_p2, "sub_ln1311_2_fu_873_p2");
    sc_trace(mVcdFile, isNeg_2_fu_865_p3, "isNeg_2_fu_865_p3");
    sc_trace(mVcdFile, sext_ln1311_4_fu_878_p1, "sext_ln1311_4_fu_878_p1");
    sc_trace(mVcdFile, ush_2_fu_882_p3, "ush_2_fu_882_p3");
    sc_trace(mVcdFile, sext_ln1311_5_fu_890_p1, "sext_ln1311_5_fu_890_p1");
    sc_trace(mVcdFile, sext_ln1311_8_fu_894_p1, "sext_ln1311_8_fu_894_p1");
    sc_trace(mVcdFile, zext_ln682_2_fu_852_p1, "zext_ln682_2_fu_852_p1");
    sc_trace(mVcdFile, zext_ln1287_2_fu_898_p1, "zext_ln1287_2_fu_898_p1");
    sc_trace(mVcdFile, r_V_4_fu_902_p2, "r_V_4_fu_902_p2");
    sc_trace(mVcdFile, tmp_27_fu_914_p3, "tmp_27_fu_914_p3");
    sc_trace(mVcdFile, r_V_5_fu_908_p2, "r_V_5_fu_908_p2");
    sc_trace(mVcdFile, zext_ln662_2_fu_922_p1, "zext_ln662_2_fu_922_p1");
    sc_trace(mVcdFile, tmp_19_fu_926_p4, "tmp_19_fu_926_p4");
    sc_trace(mVcdFile, grp_fu_178_opcode, "grp_fu_178_opcode");
    sc_trace(mVcdFile, icmp_ln16_fu_240_p2, "icmp_ln16_fu_240_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("interpolate_image.hdltvin.dat");
    mHdltvoutHandle.open("interpolate_image.hdltvout.dat");
}

interpolate_image::~interpolate_image() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete interpolate_image_faddfsub_32ns_32ns_32_4_full_dsp_1_U1;
    delete interpolate_image_fsub_32ns_32ns_32_4_full_dsp_1_U2;
    delete interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U3;
    delete interpolate_image_fmul_32ns_32ns_32_3_max_dsp_1_U4;
    delete interpolate_image_sitofp_32ns_32_4_1_U5;
    delete interpolate_image_sitofp_32s_32_4_1_U6;
}

void interpolate_image::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void interpolate_image::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read())) {
        c_0_reg_167 = c_reg_1079.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        c_0_reg_167 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && 
         esl_seteq<1,1,1>(icmp_ln21_fu_738_p2.read(), ap_const_lv1_1))) {
        x_0_reg_156 = x_reg_987.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        x_0_reg_156 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln17_fu_281_p2.read(), ap_const_lv1_1))) {
        y_0_reg_144 = y_reg_953.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        y_0_reg_144 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln21_fu_738_p2.read()))) {
        add_ln29_3_reg_1094 = add_ln29_3_fu_778_p2.read();
        add_ln29_4_reg_1099 = add_ln29_4_fu_783_p2.read();
        add_ln31_1_reg_1104 = add_ln31_1_fu_788_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        bottom_reg_1164 = grp_fu_178_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        c_reg_1079 = c_fu_744_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        dx_reg_1022 = grp_fu_178_p2.read();
        dy_reg_1028 = grp_fu_182_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        mul_ln26_reg_1034 = mul_ln26_fu_597_p2.read();
        mul_ln29_reg_1040 = mul_ln29_fu_612_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_Result_1_reg_974 = p_Val2_5_fu_264_p1.read().range(31, 31);
        p_Val2_5_reg_968 = p_Val2_5_fu_264_p1.read();
        x_assign_1_reg_958 = grp_fu_188_p2.read();
        zext_ln310_reg_963 = zext_ln310_fu_260_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        p_Val2_15_reg_1008 = p_Val2_15_fu_472_p3.read();
        p_Val2_17_reg_1015 = p_Val2_17_fu_587_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()))) {
        reg_204 = grp_fu_198_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read()))) {
        reg_210 = grp_fu_188_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()))) {
        reg_215 = grp_fu_201_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read()))) {
        reg_221 = input_image_q0.read();
        reg_225 = input_image_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read()))) {
        reg_229 = grp_fu_188_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        sub_ln26_1_reg_1056 = sub_ln26_1_fu_678_p2.read();
        sub_ln26_reg_1046 = sub_ln26_fu_642_p2.read();
        sub_ln29_1_reg_1066 = sub_ln29_1_fu_732_p2.read();
        sub_ln29_reg_1061 = sub_ln29_fu_705_p2.read();
        tmp_6_reg_1051 = grp_fu_178_p2.read();
        tmp_7_reg_1071 = grp_fu_182_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln17_fu_281_p2.read(), ap_const_lv1_0))) {
        sub_ln31_reg_1003 = sub_ln31_fu_330_p2.read();
        tmp_V_2_reg_992 = p_Val2_5_reg_968.read().range(30, 23);
        tmp_V_3_reg_998 = tmp_V_3_fu_302_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        tmp_11_reg_1144 = grp_fu_201_p1.read();
        tmp_3_reg_1139 = grp_fu_198_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        tmp_12_reg_1154 = grp_fu_194_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        tmp_1_reg_1149 = grp_fu_194_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state49.read())) {
        tmp_V_4_reg_1169 = p_Val2_10_fu_821_p1.read().range(30, 23);
        tmp_V_5_reg_1175 = tmp_V_5_fu_835_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        top_reg_1159 = grp_fu_178_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        x_reg_987 = x_fu_287_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        y_reg_953 = y_fu_246_p2.read();
    }
}

void interpolate_image::thread_add_ln26_1_fu_621_p2() {
    add_ln26_1_fu_621_p2 = (!sext_ln26_fu_618_p1.read().is_01() || !mul_ln26_reg_1034.read().is_01())? sc_lv<41>(): (sc_bigint<41>(sext_ln26_fu_618_p1.read()) + sc_biguint<41>(mul_ln26_reg_1034.read()));
}

void interpolate_image::thread_add_ln26_2_fu_657_p2() {
    add_ln26_2_fu_657_p2 = (!sext_ln26_2_fu_653_p1.read().is_01() || !mul_ln26_reg_1034.read().is_01())? sc_lv<41>(): (sc_bigint<41>(sext_ln26_2_fu_653_p1.read()) + sc_biguint<41>(mul_ln26_reg_1034.read()));
}

void interpolate_image::thread_add_ln26_3_fu_758_p2() {
    add_ln26_3_fu_758_p2 = (!zext_ln26_3_fu_754_p1.read().is_01() || !sub_ln26_reg_1046.read().is_01())? sc_lv<20>(): (sc_biguint<20>(zext_ln26_3_fu_754_p1.read()) + sc_biguint<20>(sub_ln26_reg_1046.read()));
}

void interpolate_image::thread_add_ln26_4_fu_768_p2() {
    add_ln26_4_fu_768_p2 = (!zext_ln26_3_fu_754_p1.read().is_01() || !sub_ln26_1_reg_1056.read().is_01())? sc_lv<20>(): (sc_biguint<20>(zext_ln26_3_fu_754_p1.read()) + sc_biguint<20>(sub_ln26_1_reg_1056.read()));
}

void interpolate_image::thread_add_ln26_fu_648_p2() {
    add_ln26_fu_648_p2 = (!ap_const_lv32_1.is_01() || !p_Val2_15_reg_1008.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_bigint<32>(p_Val2_15_reg_1008.read()));
}

void interpolate_image::thread_add_ln29_1_fu_684_p2() {
    add_ln29_1_fu_684_p2 = (!sext_ln26_fu_618_p1.read().is_01() || !mul_ln29_reg_1040.read().is_01())? sc_lv<41>(): (sc_bigint<41>(sext_ln26_fu_618_p1.read()) + sc_biguint<41>(mul_ln29_reg_1040.read()));
}

void interpolate_image::thread_add_ln29_2_fu_711_p2() {
    add_ln29_2_fu_711_p2 = (!sext_ln26_2_fu_653_p1.read().is_01() || !mul_ln29_reg_1040.read().is_01())? sc_lv<41>(): (sc_bigint<41>(sext_ln26_2_fu_653_p1.read()) + sc_biguint<41>(mul_ln29_reg_1040.read()));
}

void interpolate_image::thread_add_ln29_3_fu_778_p2() {
    add_ln29_3_fu_778_p2 = (!zext_ln26_3_fu_754_p1.read().is_01() || !sub_ln29_reg_1061.read().is_01())? sc_lv<20>(): (sc_biguint<20>(zext_ln26_3_fu_754_p1.read()) + sc_biguint<20>(sub_ln29_reg_1061.read()));
}

void interpolate_image::thread_add_ln29_4_fu_783_p2() {
    add_ln29_4_fu_783_p2 = (!zext_ln26_3_fu_754_p1.read().is_01() || !sub_ln29_1_reg_1066.read().is_01())? sc_lv<20>(): (sc_biguint<20>(zext_ln26_3_fu_754_p1.read()) + sc_biguint<20>(sub_ln29_1_reg_1066.read()));
}

void interpolate_image::thread_add_ln29_fu_603_p2() {
    add_ln29_fu_603_p2 = (!ap_const_lv32_1.is_01() || !p_Val2_17_reg_1015.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_bigint<32>(p_Val2_17_reg_1015.read()));
}

void interpolate_image::thread_add_ln31_1_fu_788_p2() {
    add_ln31_1_fu_788_p2 = (!zext_ln26_2_fu_750_p1.read().is_01() || !sub_ln31_reg_1003.read().is_01())? sc_lv<18>(): (sc_biguint<18>(zext_ln26_2_fu_750_p1.read()) + sc_biguint<18>(sub_ln31_reg_1003.read()));
}

void interpolate_image::thread_add_ln31_fu_309_p2() {
    add_ln31_fu_309_p2 = (!zext_ln31_fu_305_p1.read().is_01() || !zext_ln310_reg_963.read().is_01())? sc_lv<17>(): (sc_biguint<17>(zext_ln31_fu_305_p1.read()) + sc_biguint<17>(zext_ln310_reg_963.read()));
}

void interpolate_image::thread_add_ln339_1_fu_496_p2() {
    add_ln339_1_fu_496_p2 = (!ap_const_lv9_181.is_01() || !zext_ln339_1_fu_493_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(zext_ln339_1_fu_493_p1.read()));
}

void interpolate_image::thread_add_ln339_2_fu_859_p2() {
    add_ln339_2_fu_859_p2 = (!ap_const_lv9_181.is_01() || !zext_ln339_2_fu_856_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(zext_ln339_2_fu_856_p1.read()));
}

void interpolate_image::thread_add_ln339_fu_380_p2() {
    add_ln339_fu_380_p2 = (!ap_const_lv9_181.is_01() || !zext_ln339_fu_376_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(zext_ln339_fu_376_p1.read()));
}

void interpolate_image::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void interpolate_image::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void interpolate_image::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void interpolate_image::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void interpolate_image::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void interpolate_image::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void interpolate_image::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void interpolate_image::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void interpolate_image::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void interpolate_image::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void interpolate_image::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void interpolate_image::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void interpolate_image::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void interpolate_image::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void interpolate_image::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void interpolate_image::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void interpolate_image::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void interpolate_image::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void interpolate_image::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void interpolate_image::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void interpolate_image::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[36];
}

void interpolate_image::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[37];
}

void interpolate_image::thread_ap_CS_fsm_state39() {
    ap_CS_fsm_state39 = ap_CS_fsm.read()[38];
}

void interpolate_image::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void interpolate_image::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void interpolate_image::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void interpolate_image::thread_ap_CS_fsm_state44() {
    ap_CS_fsm_state44 = ap_CS_fsm.read()[43];
}

void interpolate_image::thread_ap_CS_fsm_state45() {
    ap_CS_fsm_state45 = ap_CS_fsm.read()[44];
}

void interpolate_image::thread_ap_CS_fsm_state46() {
    ap_CS_fsm_state46 = ap_CS_fsm.read()[45];
}

void interpolate_image::thread_ap_CS_fsm_state49() {
    ap_CS_fsm_state49 = ap_CS_fsm.read()[48];
}

void interpolate_image::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void interpolate_image::thread_ap_CS_fsm_state50() {
    ap_CS_fsm_state50 = ap_CS_fsm.read()[49];
}

void interpolate_image::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void interpolate_image::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void interpolate_image::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void interpolate_image::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln16_fu_240_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void interpolate_image::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void interpolate_image::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln16_fu_240_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void interpolate_image::thread_c_fu_744_p2() {
    c_fu_744_p2 = (!c_0_reg_167.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_0_reg_167.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void interpolate_image::thread_grp_fu_178_opcode() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        grp_fu_178_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()))) {
        grp_fu_178_opcode = ap_const_lv2_0;
    } else {
        grp_fu_178_opcode = "XX";
    }
}

void interpolate_image::thread_grp_fu_178_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        grp_fu_178_p0 = reg_229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        grp_fu_178_p0 = ap_const_lv32_3F800000;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()))) {
        grp_fu_178_p0 = reg_210.read();
    } else {
        grp_fu_178_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_178_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read())) {
        grp_fu_178_p1 = reg_229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        grp_fu_178_p1 = tmp_12_reg_1154.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_178_p1 = tmp_1_reg_1149.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        grp_fu_178_p1 = dx_reg_1022.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_178_p1 = reg_204.read();
    } else {
        grp_fu_178_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_182_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        grp_fu_182_p0 = ap_const_lv32_3F800000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_182_p0 = x_assign_1_reg_958.read();
    } else {
        grp_fu_182_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_182_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        grp_fu_182_p1 = dy_reg_1028.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        grp_fu_182_p1 = reg_215.read();
    } else {
        grp_fu_182_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_188_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_188_p0 = bottom_reg_1164.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        grp_fu_188_p0 = top_reg_1159.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        grp_fu_188_p0 = tmp_3_reg_1139.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        grp_fu_188_p0 = reg_204.read();
    } else {
        grp_fu_188_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_188_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        grp_fu_188_p1 = dy_reg_1028.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        grp_fu_188_p1 = tmp_7_reg_1071.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read()))) {
        grp_fu_188_p1 = tmp_6_reg_1051.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_188_p1 = ap_const_lv32_3FD88000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_188_p1 = ap_const_lv32_40210000;
    } else {
        grp_fu_188_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_194_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state36.read())) {
        grp_fu_194_p0 = tmp_11_reg_1144.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        grp_fu_194_p0 = reg_215.read();
    } else {
        grp_fu_194_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_198_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_198_p0 = zext_ln29_fu_811_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_198_p0 = zext_ln26_fu_801_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_198_p0 = p_Val2_15_reg_1008.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        grp_fu_198_p0 = zext_ln17_fu_276_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_198_p0 = zext_ln16_fu_235_p1.read();
    } else {
        grp_fu_198_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_grp_fu_201_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        grp_fu_201_p0 = zext_ln29_1_fu_816_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        grp_fu_201_p0 = zext_ln26_1_fu_806_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_201_p0 = p_Val2_17_reg_1015.read();
    } else {
        grp_fu_201_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_icmp_ln16_fu_240_p2() {
    icmp_ln16_fu_240_p2 = (!y_0_reg_144.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_144.read() == ap_const_lv8_80);
}

void interpolate_image::thread_icmp_ln17_fu_281_p2() {
    icmp_ln17_fu_281_p2 = (!x_0_reg_156.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_156.read() == ap_const_lv9_100);
}

void interpolate_image::thread_icmp_ln21_fu_738_p2() {
    icmp_ln21_fu_738_p2 = (!c_0_reg_167.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_167.read() == ap_const_lv2_3);
}

void interpolate_image::thread_input_image_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
        input_image_address0 =  (sc_lv<19>) (zext_ln29_2_fu_793_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        input_image_address0 =  (sc_lv<19>) (zext_ln26_4_fu_763_p1.read());
    } else {
        input_image_address0 =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_input_image_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read())) {
        input_image_address1 =  (sc_lv<19>) (zext_ln29_3_fu_797_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read())) {
        input_image_address1 =  (sc_lv<19>) (zext_ln26_5_fu_773_p1.read());
    } else {
        input_image_address1 =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
    }
}

void interpolate_image::thread_input_image_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()))) {
        input_image_ce0 = ap_const_logic_1;
    } else {
        input_image_ce0 = ap_const_logic_0;
    }
}

void interpolate_image::thread_input_image_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state30.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()))) {
        input_image_ce1 = ap_const_logic_1;
    } else {
        input_image_ce1 = ap_const_logic_0;
    }
}

void interpolate_image::thread_isNeg_1_fu_502_p3() {
    isNeg_1_fu_502_p3 = add_ln339_1_fu_496_p2.read().range(8, 8);
}

void interpolate_image::thread_isNeg_2_fu_865_p3() {
    isNeg_2_fu_865_p3 = add_ln339_2_fu_859_p2.read().range(8, 8);
}

void interpolate_image::thread_isNeg_fu_386_p3() {
    isNeg_fu_386_p3 = add_ln339_fu_380_p2.read().range(8, 8);
}

void interpolate_image::thread_mantissa_V_1_fu_480_p4() {
    mantissa_V_1_fu_480_p4 = esl_concat<24,1>(esl_concat<1,23>(ap_const_lv1_1, tmp_V_3_reg_998.read()), ap_const_lv1_0);
}

void interpolate_image::thread_mantissa_V_2_fu_843_p4() {
    mantissa_V_2_fu_843_p4 = esl_concat<24,1>(esl_concat<1,23>(ap_const_lv1_1, tmp_V_5_reg_1175.read()), ap_const_lv1_0);
}

void interpolate_image::thread_mantissa_V_fu_362_p4() {
    mantissa_V_fu_362_p4 = esl_concat<24,1>(esl_concat<1,23>(ap_const_lv1_1, tmp_V_1_fu_358_p1.read()), ap_const_lv1_0);
}

void interpolate_image::thread_mul_ln26_fu_597_p1() {
    mul_ln26_fu_597_p1 = p_Val2_17_reg_1015.read();
}

void interpolate_image::thread_mul_ln26_fu_597_p2() {
    mul_ln26_fu_597_p2 = (!ap_const_lv41_1B2.is_01() || !mul_ln26_fu_597_p1.read().is_01())? sc_lv<41>(): sc_biguint<41>(ap_const_lv41_1B2) * sc_bigint<32>(mul_ln26_fu_597_p1.read());
}

void interpolate_image::thread_mul_ln29_fu_612_p1() {
    mul_ln29_fu_612_p1 = add_ln29_fu_603_p2.read();
}

void interpolate_image::thread_mul_ln29_fu_612_p2() {
    mul_ln29_fu_612_p2 = (!ap_const_lv41_1B2.is_01() || !mul_ln29_fu_612_p1.read().is_01())? sc_lv<41>(): sc_biguint<41>(ap_const_lv41_1B2) * sc_bigint<32>(mul_ln29_fu_612_p1.read());
}

void interpolate_image::thread_output_image_address0() {
    output_image_address0 =  (sc_lv<17>) (zext_ln31_2_fu_839_p1.read());
}

void interpolate_image::thread_output_image_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read())) {
        output_image_ce0 = ap_const_logic_1;
    } else {
        output_image_ce0 = ap_const_logic_0;
    }
}

void interpolate_image::thread_output_image_d0() {
    output_image_d0 = (!isNeg_2_fu_865_p3.read()[0].is_01())? sc_lv<8>(): ((isNeg_2_fu_865_p3.read()[0].to_bool())? zext_ln662_2_fu_922_p1.read(): tmp_19_fu_926_p4.read());
}

void interpolate_image::thread_output_image_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read())) {
        output_image_we0 = ap_const_logic_1;
    } else {
        output_image_we0 = ap_const_logic_0;
    }
}

void interpolate_image::thread_p_Result_s_fu_340_p3() {
    p_Result_s_fu_340_p3 = p_Val2_s_fu_336_p1.read().range(31, 31);
}

void interpolate_image::thread_p_Val2_10_fu_821_p1() {
    p_Val2_10_fu_821_p1 = grp_fu_178_p2.read();
}

void interpolate_image::thread_p_Val2_14_fu_458_p3() {
    p_Val2_14_fu_458_p3 = (!isNeg_fu_386_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_386_p3.read()[0].to_bool())? zext_ln662_fu_444_p1.read(): tmp_17_fu_448_p4.read());
}

void interpolate_image::thread_p_Val2_15_fu_472_p3() {
    p_Val2_15_fu_472_p3 = (!p_Result_s_fu_340_p3.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_fu_340_p3.read()[0].to_bool())? result_V_1_fu_466_p2.read(): p_Val2_14_fu_458_p3.read());
}

void interpolate_image::thread_p_Val2_16_fu_573_p3() {
    p_Val2_16_fu_573_p3 = (!isNeg_1_fu_502_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_1_fu_502_p3.read()[0].to_bool())? zext_ln662_1_fu_559_p1.read(): tmp_18_fu_563_p4.read());
}

void interpolate_image::thread_p_Val2_17_fu_587_p3() {
    p_Val2_17_fu_587_p3 = (!p_Result_1_reg_974.read()[0].is_01())? sc_lv<32>(): ((p_Result_1_reg_974.read()[0].to_bool())? result_V_3_fu_581_p2.read(): p_Val2_16_fu_573_p3.read());
}

void interpolate_image::thread_p_Val2_5_fu_264_p1() {
    p_Val2_5_fu_264_p1 = grp_fu_188_p2.read();
}

void interpolate_image::thread_p_Val2_s_fu_336_p1() {
    p_Val2_s_fu_336_p1 = reg_210.read();
}

void interpolate_image::thread_p_shl1_cast_fu_724_p3() {
    p_shl1_cast_fu_724_p3 = esl_concat<18,2>(trunc_ln29_3_fu_720_p1.read(), ap_const_lv2_0);
}

void interpolate_image::thread_p_shl2_cast_fu_697_p3() {
    p_shl2_cast_fu_697_p3 = esl_concat<18,2>(trunc_ln29_1_fu_693_p1.read(), ap_const_lv2_0);
}

void interpolate_image::thread_p_shl3_cast_fu_670_p3() {
    p_shl3_cast_fu_670_p3 = esl_concat<18,2>(trunc_ln26_3_fu_666_p1.read(), ap_const_lv2_0);
}

void interpolate_image::thread_p_shl4_cast_fu_634_p3() {
    p_shl4_cast_fu_634_p3 = esl_concat<18,2>(trunc_ln26_1_fu_630_p1.read(), ap_const_lv2_0);
}

void interpolate_image::thread_p_shl_cast_fu_322_p3() {
    p_shl_cast_fu_322_p3 = esl_concat<16,2>(trunc_ln31_fu_318_p1.read(), ap_const_lv2_0);
}

void interpolate_image::thread_r_V_1_fu_430_p2() {
    r_V_1_fu_430_p2 = (!zext_ln1287_fu_420_p1.read().is_01())? sc_lv<79>(): zext_ln682_fu_372_p1.read() << (unsigned short)zext_ln1287_fu_420_p1.read().to_uint();
}

void interpolate_image::thread_r_V_2_fu_539_p2() {
    r_V_2_fu_539_p2 = (!sext_ln1311_7_fu_531_p1.read().is_01())? sc_lv<25>(): mantissa_V_1_fu_480_p4.read() >> (unsigned short)sext_ln1311_7_fu_531_p1.read().to_uint();
}

void interpolate_image::thread_r_V_3_fu_545_p2() {
    r_V_3_fu_545_p2 = (!zext_ln1287_1_fu_535_p1.read().is_01())? sc_lv<79>(): zext_ln682_1_fu_489_p1.read() << (unsigned short)zext_ln1287_1_fu_535_p1.read().to_uint();
}

void interpolate_image::thread_r_V_4_fu_902_p2() {
    r_V_4_fu_902_p2 = (!sext_ln1311_8_fu_894_p1.read().is_01())? sc_lv<25>(): mantissa_V_2_fu_843_p4.read() >> (unsigned short)sext_ln1311_8_fu_894_p1.read().to_uint();
}

void interpolate_image::thread_r_V_5_fu_908_p2() {
    r_V_5_fu_908_p2 = (!zext_ln1287_2_fu_898_p1.read().is_01())? sc_lv<55>(): zext_ln682_2_fu_852_p1.read() << (unsigned short)zext_ln1287_2_fu_898_p1.read().to_uint();
}

void interpolate_image::thread_r_V_fu_424_p2() {
    r_V_fu_424_p2 = (!sext_ln1311_6_fu_416_p1.read().is_01())? sc_lv<25>(): mantissa_V_fu_362_p4.read() >> (unsigned short)sext_ln1311_6_fu_416_p1.read().to_uint();
}

void interpolate_image::thread_result_V_1_fu_466_p2() {
    result_V_1_fu_466_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_14_fu_458_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_14_fu_458_p3.read()));
}

void interpolate_image::thread_result_V_3_fu_581_p2() {
    result_V_3_fu_581_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_16_fu_573_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_16_fu_573_p3.read()));
}

void interpolate_image::thread_sext_ln1311_1_fu_412_p1() {
    sext_ln1311_1_fu_412_p1 = esl_sext<32,9>(ush_fu_404_p3.read());
}

void interpolate_image::thread_sext_ln1311_2_fu_515_p1() {
    sext_ln1311_2_fu_515_p1 = esl_sext<9,8>(sub_ln1311_1_fu_510_p2.read());
}

void interpolate_image::thread_sext_ln1311_3_fu_527_p1() {
    sext_ln1311_3_fu_527_p1 = esl_sext<32,9>(ush_1_fu_519_p3.read());
}

void interpolate_image::thread_sext_ln1311_4_fu_878_p1() {
    sext_ln1311_4_fu_878_p1 = esl_sext<9,8>(sub_ln1311_2_fu_873_p2.read());
}

void interpolate_image::thread_sext_ln1311_5_fu_890_p1() {
    sext_ln1311_5_fu_890_p1 = esl_sext<32,9>(ush_2_fu_882_p3.read());
}

void interpolate_image::thread_sext_ln1311_6_fu_416_p1() {
    sext_ln1311_6_fu_416_p1 = esl_sext<25,9>(ush_fu_404_p3.read());
}

void interpolate_image::thread_sext_ln1311_7_fu_531_p1() {
    sext_ln1311_7_fu_531_p1 = esl_sext<25,9>(ush_1_fu_519_p3.read());
}

void interpolate_image::thread_sext_ln1311_8_fu_894_p1() {
    sext_ln1311_8_fu_894_p1 = esl_sext<25,9>(ush_2_fu_882_p3.read());
}

void interpolate_image::thread_sext_ln1311_fu_400_p1() {
    sext_ln1311_fu_400_p1 = esl_sext<9,8>(sub_ln1311_fu_394_p2.read());
}

void interpolate_image::thread_sext_ln26_2_fu_653_p1() {
    sext_ln26_2_fu_653_p1 = esl_sext<41,32>(add_ln26_fu_648_p2.read());
}

void interpolate_image::thread_sext_ln26_fu_618_p1() {
    sext_ln26_fu_618_p1 = esl_sext<41,32>(p_Val2_15_reg_1008.read());
}

void interpolate_image::thread_sub_ln1311_1_fu_510_p2() {
    sub_ln1311_1_fu_510_p2 = (!ap_const_lv8_7F.is_01() || !tmp_V_2_reg_992.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(tmp_V_2_reg_992.read()));
}

void interpolate_image::thread_sub_ln1311_2_fu_873_p2() {
    sub_ln1311_2_fu_873_p2 = (!ap_const_lv8_7F.is_01() || !tmp_V_4_reg_1169.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(tmp_V_4_reg_1169.read()));
}

void interpolate_image::thread_sub_ln1311_fu_394_p2() {
    sub_ln1311_fu_394_p2 = (!ap_const_lv8_7F.is_01() || !tmp_V_fu_348_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(tmp_V_fu_348_p4.read()));
}

void interpolate_image::thread_sub_ln26_1_fu_678_p2() {
    sub_ln26_1_fu_678_p2 = (!p_shl3_cast_fu_670_p3.read().is_01() || !trunc_ln26_2_fu_662_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl3_cast_fu_670_p3.read()) - sc_biguint<20>(trunc_ln26_2_fu_662_p1.read()));
}

void interpolate_image::thread_sub_ln26_fu_642_p2() {
    sub_ln26_fu_642_p2 = (!p_shl4_cast_fu_634_p3.read().is_01() || !trunc_ln26_fu_626_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl4_cast_fu_634_p3.read()) - sc_biguint<20>(trunc_ln26_fu_626_p1.read()));
}

void interpolate_image::thread_sub_ln29_1_fu_732_p2() {
    sub_ln29_1_fu_732_p2 = (!p_shl1_cast_fu_724_p3.read().is_01() || !trunc_ln29_2_fu_716_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl1_cast_fu_724_p3.read()) - sc_biguint<20>(trunc_ln29_2_fu_716_p1.read()));
}

void interpolate_image::thread_sub_ln29_fu_705_p2() {
    sub_ln29_fu_705_p2 = (!p_shl2_cast_fu_697_p3.read().is_01() || !trunc_ln29_fu_689_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(p_shl2_cast_fu_697_p3.read()) - sc_biguint<20>(trunc_ln29_fu_689_p1.read()));
}

void interpolate_image::thread_sub_ln31_fu_330_p2() {
    sub_ln31_fu_330_p2 = (!p_shl_cast_fu_322_p3.read().is_01() || !zext_ln31_1_fu_314_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_shl_cast_fu_322_p3.read()) - sc_biguint<18>(zext_ln31_1_fu_314_p1.read()));
}

void interpolate_image::thread_tmp_15_fu_252_p3() {
    tmp_15_fu_252_p3 = esl_concat<8,8>(y_0_reg_144.read(), ap_const_lv8_0);
}

void interpolate_image::thread_tmp_17_fu_448_p4() {
    tmp_17_fu_448_p4 = r_V_1_fu_430_p2.read().range(55, 24);
}

void interpolate_image::thread_tmp_18_fu_563_p4() {
    tmp_18_fu_563_p4 = r_V_3_fu_545_p2.read().range(55, 24);
}

void interpolate_image::thread_tmp_19_fu_926_p4() {
    tmp_19_fu_926_p4 = r_V_5_fu_908_p2.read().range(31, 24);
}

void interpolate_image::thread_tmp_21_fu_436_p3() {
    tmp_21_fu_436_p3 = r_V_fu_424_p2.read().range(24, 24);
}

void interpolate_image::thread_tmp_23_fu_551_p3() {
    tmp_23_fu_551_p3 = r_V_2_fu_539_p2.read().range(24, 24);
}

void interpolate_image::thread_tmp_27_fu_914_p3() {
    tmp_27_fu_914_p3 = r_V_4_fu_902_p2.read().range(24, 24);
}

void interpolate_image::thread_tmp_V_1_fu_358_p1() {
    tmp_V_1_fu_358_p1 = p_Val2_s_fu_336_p1.read().range(23-1, 0);
}

void interpolate_image::thread_tmp_V_3_fu_302_p1() {
    tmp_V_3_fu_302_p1 = p_Val2_5_reg_968.read().range(23-1, 0);
}

void interpolate_image::thread_tmp_V_5_fu_835_p1() {
    tmp_V_5_fu_835_p1 = p_Val2_10_fu_821_p1.read().range(23-1, 0);
}

void interpolate_image::thread_tmp_V_fu_348_p4() {
    tmp_V_fu_348_p4 = p_Val2_s_fu_336_p1.read().range(30, 23);
}

void interpolate_image::thread_trunc_ln26_1_fu_630_p1() {
    trunc_ln26_1_fu_630_p1 = add_ln26_1_fu_621_p2.read().range(18-1, 0);
}

void interpolate_image::thread_trunc_ln26_2_fu_662_p1() {
    trunc_ln26_2_fu_662_p1 = add_ln26_2_fu_657_p2.read().range(20-1, 0);
}

void interpolate_image::thread_trunc_ln26_3_fu_666_p1() {
    trunc_ln26_3_fu_666_p1 = add_ln26_2_fu_657_p2.read().range(18-1, 0);
}

void interpolate_image::thread_trunc_ln26_fu_626_p1() {
    trunc_ln26_fu_626_p1 = add_ln26_1_fu_621_p2.read().range(20-1, 0);
}

void interpolate_image::thread_trunc_ln29_1_fu_693_p1() {
    trunc_ln29_1_fu_693_p1 = add_ln29_1_fu_684_p2.read().range(18-1, 0);
}

void interpolate_image::thread_trunc_ln29_2_fu_716_p1() {
    trunc_ln29_2_fu_716_p1 = add_ln29_2_fu_711_p2.read().range(20-1, 0);
}

void interpolate_image::thread_trunc_ln29_3_fu_720_p1() {
    trunc_ln29_3_fu_720_p1 = add_ln29_2_fu_711_p2.read().range(18-1, 0);
}

void interpolate_image::thread_trunc_ln29_fu_689_p1() {
    trunc_ln29_fu_689_p1 = add_ln29_1_fu_684_p2.read().range(20-1, 0);
}

void interpolate_image::thread_trunc_ln31_fu_318_p1() {
    trunc_ln31_fu_318_p1 = add_ln31_fu_309_p2.read().range(16-1, 0);
}

void interpolate_image::thread_ush_1_fu_519_p3() {
    ush_1_fu_519_p3 = (!isNeg_1_fu_502_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_1_fu_502_p3.read()[0].to_bool())? sext_ln1311_2_fu_515_p1.read(): add_ln339_1_fu_496_p2.read());
}

void interpolate_image::thread_ush_2_fu_882_p3() {
    ush_2_fu_882_p3 = (!isNeg_2_fu_865_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_2_fu_865_p3.read()[0].to_bool())? sext_ln1311_4_fu_878_p1.read(): add_ln339_2_fu_859_p2.read());
}

void interpolate_image::thread_ush_fu_404_p3() {
    ush_fu_404_p3 = (!isNeg_fu_386_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_386_p3.read()[0].to_bool())? sext_ln1311_fu_400_p1.read(): add_ln339_fu_380_p2.read());
}

void interpolate_image::thread_x_fu_287_p2() {
    x_fu_287_p2 = (!x_0_reg_156.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(x_0_reg_156.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void interpolate_image::thread_y_fu_246_p2() {
    y_fu_246_p2 = (!y_0_reg_144.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(y_0_reg_144.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void interpolate_image::thread_zext_ln1287_1_fu_535_p1() {
    zext_ln1287_1_fu_535_p1 = esl_zext<79,32>(sext_ln1311_3_fu_527_p1.read());
}

void interpolate_image::thread_zext_ln1287_2_fu_898_p1() {
    zext_ln1287_2_fu_898_p1 = esl_zext<55,32>(sext_ln1311_5_fu_890_p1.read());
}

void interpolate_image::thread_zext_ln1287_fu_420_p1() {
    zext_ln1287_fu_420_p1 = esl_zext<79,32>(sext_ln1311_1_fu_412_p1.read());
}

void interpolate_image::thread_zext_ln16_fu_235_p1() {
    zext_ln16_fu_235_p1 = esl_zext<32,8>(y_0_reg_144.read());
}

void interpolate_image::thread_zext_ln17_fu_276_p1() {
    zext_ln17_fu_276_p1 = esl_zext<32,9>(x_0_reg_156.read());
}

void interpolate_image::thread_zext_ln26_1_fu_806_p1() {
    zext_ln26_1_fu_806_p1 = esl_zext<32,8>(reg_225.read());
}

void interpolate_image::thread_zext_ln26_2_fu_750_p1() {
    zext_ln26_2_fu_750_p1 = esl_zext<18,2>(c_0_reg_167.read());
}

void interpolate_image::thread_zext_ln26_3_fu_754_p1() {
    zext_ln26_3_fu_754_p1 = esl_zext<20,2>(c_0_reg_167.read());
}

void interpolate_image::thread_zext_ln26_4_fu_763_p1() {
    zext_ln26_4_fu_763_p1 = esl_zext<64,20>(add_ln26_3_fu_758_p2.read());
}

void interpolate_image::thread_zext_ln26_5_fu_773_p1() {
    zext_ln26_5_fu_773_p1 = esl_zext<64,20>(add_ln26_4_fu_768_p2.read());
}

void interpolate_image::thread_zext_ln26_fu_801_p1() {
    zext_ln26_fu_801_p1 = esl_zext<32,8>(reg_221.read());
}

void interpolate_image::thread_zext_ln29_1_fu_816_p1() {
    zext_ln29_1_fu_816_p1 = esl_zext<32,8>(reg_225.read());
}

void interpolate_image::thread_zext_ln29_2_fu_793_p1() {
    zext_ln29_2_fu_793_p1 = esl_zext<64,20>(add_ln29_3_reg_1094.read());
}

void interpolate_image::thread_zext_ln29_3_fu_797_p1() {
    zext_ln29_3_fu_797_p1 = esl_zext<64,20>(add_ln29_4_reg_1099.read());
}

void interpolate_image::thread_zext_ln29_fu_811_p1() {
    zext_ln29_fu_811_p1 = esl_zext<32,8>(reg_221.read());
}

void interpolate_image::thread_zext_ln310_fu_260_p1() {
    zext_ln310_fu_260_p1 = esl_zext<17,16>(tmp_15_fu_252_p3.read());
}

void interpolate_image::thread_zext_ln31_1_fu_314_p1() {
    zext_ln31_1_fu_314_p1 = esl_zext<18,17>(add_ln31_fu_309_p2.read());
}

void interpolate_image::thread_zext_ln31_2_fu_839_p1() {
    zext_ln31_2_fu_839_p1 = esl_zext<64,18>(add_ln31_1_reg_1104.read());
}

void interpolate_image::thread_zext_ln31_fu_305_p1() {
    zext_ln31_fu_305_p1 = esl_zext<17,9>(x_0_reg_156.read());
}

void interpolate_image::thread_zext_ln339_1_fu_493_p1() {
    zext_ln339_1_fu_493_p1 = esl_zext<9,8>(tmp_V_2_reg_992.read());
}

void interpolate_image::thread_zext_ln339_2_fu_856_p1() {
    zext_ln339_2_fu_856_p1 = esl_zext<9,8>(tmp_V_4_reg_1169.read());
}

void interpolate_image::thread_zext_ln339_fu_376_p1() {
    zext_ln339_fu_376_p1 = esl_zext<9,8>(tmp_V_fu_348_p4.read());
}

void interpolate_image::thread_zext_ln662_1_fu_559_p1() {
    zext_ln662_1_fu_559_p1 = esl_zext<32,1>(tmp_23_fu_551_p3.read());
}

void interpolate_image::thread_zext_ln662_2_fu_922_p1() {
    zext_ln662_2_fu_922_p1 = esl_zext<8,1>(tmp_27_fu_914_p3.read());
}

void interpolate_image::thread_zext_ln662_fu_444_p1() {
    zext_ln662_fu_444_p1 = esl_zext<32,1>(tmp_21_fu_436_p3.read());
}

void interpolate_image::thread_zext_ln682_1_fu_489_p1() {
    zext_ln682_1_fu_489_p1 = esl_zext<79,25>(mantissa_V_1_fu_480_p4.read());
}

void interpolate_image::thread_zext_ln682_2_fu_852_p1() {
    zext_ln682_2_fu_852_p1 = esl_zext<55,25>(mantissa_V_2_fu_843_p4.read());
}

void interpolate_image::thread_zext_ln682_fu_372_p1() {
    zext_ln682_fu_372_p1 = esl_zext<79,25>(mantissa_V_fu_362_p4.read());
}

void interpolate_image::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln16_fu_240_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln17_fu_281_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) && esl_seteq<1,1,1>(icmp_ln21_fu_738_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state30;
            }
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state45;
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_fsm_state46;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_fsm_state47;
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_fsm_state48;
            break;
        case 140737488355328 : 
            ap_NS_fsm = ap_ST_fsm_state49;
            break;
        case 281474976710656 : 
            ap_NS_fsm = ap_ST_fsm_state50;
            break;
        case 562949953421312 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<50>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void interpolate_image::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_image_address0\" :  \"" << input_image_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_image_ce0\" :  \"" << input_image_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_image_q0\" :  \"" << input_image_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_image_address1\" :  \"" << input_image_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_image_ce1\" :  \"" << input_image_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_image_q1\" :  \"" << input_image_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_address0\" :  \"" << output_image_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_ce0\" :  \"" << output_image_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_we0\" :  \"" << output_image_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_d0\" :  \"" << output_image_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

